services:
  virtusbaseweb:
    build:
      context: .
      dockerfile: Dockerfiles/DockerfileFrontend
    ports:
      - "3000:80"  # Changed from 3000:3000 to 3000:80
    volumes:
      - ./virtusbaseweb:/app
      - /app/node_modules
    networks:
      - app-network

  virtusbaseapp:
    build:
      context: .
      dockerfile: Dockerfiles/DockerfileIonic
    ports:
      - "3100:8100"
    volumes:
      - ./virtusbaseapp:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfiles/DockerfileBackend
    volumes:
        - ./backend/virtusbasebackend:/var/www
    ports: # Changed from expose to ports
        - "3200:9000"
    networks:
        - app-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
        - "3300:80"
    volumes:
        - ./backend/virtusbasebackend:/var/www
        - ./Dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
        - app-network
    depends_on:
        - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: jonas
      MYSQL_PASSWORD: geheim
      MYSQL_ROOT_PASSWORD: rootgeheim
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "3400:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootgeheim
    depends_on:
      - db
    networks:
      - app-network    

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge